apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{deployment-name}#
  labels:
    app: #{deployment-name}#
spec:
  replicas: #{deployment-replicas}#
  selector:
    matchLabels:
      app: #{deployment-name}#
  template:
    metadata:
      labels:
        app: #{deployment-name}#
    spec:
      containers:
      - name: #{deployment-name}#
        image: #{acr-name}#.azurecr.io/ado-windows-agent:#{image-tag}#
        ports:
        - containerPort: 443
        imagePullPolicy: Always
        volumeMounts:
          - name: docker-pipe
            mountPath: \\.\pipe\docker_engine
        securityContext:
          privileged: true
      nodeSelector:
          "beta.kubernetes.io/os": windows
      volumes:
        - name: docker-pipe
          hostPath: 
            path: \\.\pipe\docker_engine
            type: null
