$AGENT_NAME = hostname

New-Item $env:AZP_WORK -ItemType directory | Out-Null
Set-Location agent

$env:VSO_AGENT_IGNORE = "$env:VSO_AGENT_IGNORE,__DOTNET_ADD_32BIT,__DOTNET_PREFERRED_BITNESS,__VSCMD_PREINIT_PATH"
$env:VSO_AGENT_IGNORE = "$env:VSO_AGENT_IGNORE,ALLUSERSPROFILE,APPDATA,Cmd,COMPLUS_NGenProtectedProcess_FeatureEnabled,ComSpec,DOTNET_SKIP_FIRST_TIME_EXPERIENCE,DriverData,INCLUDE,InteractiveSession,LOCALAPPDATA"
$env:VSO_AGENT_IGNORE = "$env:VSO_AGENT_IGNORE,AZP_POOL,AZP_URL,AZP_WORK"
$env:VSO_AGENT_IGNORE = "$env:VSO_AGENT_IGNORE,KUBERNETES_PORT,KUBERNETES_PORT_443_TCP,KUBERNETES_PORT_443_TCP_ADDR,KUBERNETES_PORT_443_TCP_PORT,KUBERNETES_PORT_443_TCP_PROTO,KUBERNETES_SERVICE_HOST,KUBERNETES_SERVICE_PORT,KUBERNETES_SERVICE_PORT_HTTPS"
$env:VSO_AGENT_IGNORE = "$env:VSO_AGENT_IGNORE,NUMBER_OF_PROCESSORS,OS,Path,PATHEXT,PROCESSOR_ARCHITECTURE,PROCESSOR_IDENTIFIER,PROCESSOR_LEVEL,PROCESSOR_REVISION"
$env:VSO_AGENT_IGNORE = "$env:VSO_AGENT_IGNORE,ADO_AGENT_URL,ANT_URL,AZ_COPY_URL,CLOUD_FOUNDRY_CLI_URL,DOTNET_CORE_URL,GCLOUD_SDK_URL,GO_URL,GRADLE_URL,KUBECTL_URL,MAVEN_URL,MYSQL_URL,NODEJS_URL,RUBY_URL,RUBYOPT,SALESFORCE_CLI_URL,PYTHON3_URL,HELM2_URL,HELM3_URL,JDK_URL,JQ_URL,CMAKE_URL,CURL_URL,GIT_URL,PACKER_URL,TERRAFORM_URL,VAULT_URL"
$env:VSO_AGENT_IGNORE = "$env:VSO_AGENT_IGNORE,PROMPT,PSExecutionPolicyPreference,PSModulePath,PUBLIC,SystemDrive,SystemRoot,USERNAME,TEMP,TMP,USERDOMAIN,VERBOSE_ARG,VSCMD_ARG_app_plat,VSCMD_ARG_HOST_ARCH,VSCMD_ARG_TGT_ARCH,VSO_AGENT_IGNORE,windir,WindowsLibPath,WindowsSDKVersion"

cd C:\azp\agent
.\config.cmd --unattended `
    --agent "$AGENT_NAME" `
    --url "$env:AZP_URL" `
    --auth PAT `
    --token "$env:AZP_TOKEN" `
    --pool "$env:AZP_POOL" `
    --work "$env:AZP_WORK" `
    --replace

$env:AZP_TOKEN = $null

.\run.cmd --once
